add(09) function basics

diff --git a/.github/workflows/09-functions.yaml b/.github/workflows/09-functions.yaml
--- a/.github/workflows/09-functions.yaml
+++ b/.github/workflows/09-functions.yaml
@@ -1,31 +1,43 @@
 name: 09 - Using Functions
 on:
-    workflow_dispatch:
-    pull_request:
+  workflow_dispatch:
+  pull_request:
 
 jobs:
-    echo1:
-        runs-on: ubuntu-latest
-        steps:
+  echo1:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Print PR title
+        run: echo "The PR title is ${{ github.event.pull_request.title }}"
 
-            - name: Failing step
-              run : exit 0
-            
-            - name: I will be skipped
-              if: ${{ success() }}
-              run : echo "I will print if previous steps succeed."
-        
-            - name: I will execute
-              if: ${{ failure() }}
-              run : echo "I will print if any previous step fails."
-            
-            - name: I will execute
-              if: ${{ !cancelled() }}
-              run : echo "I will always print, except when the workflow is cancelled."
-            
-            - name: Sleep for 20 seconds
-              run: sleep 20
+      - name: Print PR Labels
+        run: | 
+            cat << EOF
+            ${{ toJSON(github.event.pull_request.labels) }}
+            EOF
 
-            - name: I will execute when cancelled,
-              if: ${{ cancelled() }}
-              run : echo "I will print if the workflow has been cancelled"
+      - name: Bug step
+        if: ${{ !cancelled() && contains(github.event.pull_request.title, 'fix') }}
+        run: echo "I am a bug fix"
+
+      - name: Failing step
+        run: exit 1
+
+      - name: I will be skipped
+        if: ${{ success() }}
+        run: echo "I will print if previous steps succeed."
+
+      - name: I will execute
+        if: ${{ failure() }}
+        run: echo "I will print if any previous step fails."
+
+      - name: I will execute
+        if: ${{ !cancelled() }}
+        run: echo "I will always print, except when the workflow is cancelled."
+
+      - name: Sleep for 20 seconds
+        run: sleep 20
+
+      - name: I will execute when cancelled
+        if: ${{ cancelled() }}
+        run: echo "I will print if the workflow has been cancelled"
